version: 0.0
os: linux
files:
  - source: dist
    destination: /var/www/website
permissions:
  - object: /var/www/website
    pattern: "**"
    mode: "0755"
    owner: root
    group: root
    type:
      - file
      - directory
hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300
